version: '3.9' # optional since v1.27.0
services:

  shishahub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - '3010:3010'
    expose:
    - 3010
    env_file: ./.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      SESSION_SECRET: ${SESSION_SECRET}
      VIRTUAL_HOST: shishahub.online # the incomming domain name for this site
      VIRTUAL_PORT: 3010 # the port your applicatio

networks:
  default:
    external:
      name: nginx-proxy