version: '3.9' # optional since v1.27.0
services:
#   shishahub-db:
#     image: mysql:5.7
#     restart: unless-stopped
#     # ports:
#       # - '3306:3306'
#     # command: --default-authentication-plugin=mysql_native_password
#     env_file: ./.env
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_DATABASE}
#     volumes:
#       - db_data:/var/lib/mysql
# #     networks:
# #       - mynet

  shishahub-backend:
    # depends_on:
    #   - docker-db
    networks:
      - host
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - '3010:3010'
    # env_file: ./.env
    # environment:
    #   MYSQL_DATABASE: ${DB_DATABASE}
    #   MYSQL_USER: ${DB_USER}
    #   MYSQL_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_HOST: docker-db
    #   SESSION_SECRET: ${SESSION_SECRET}
    #   FRONT_END_IP: ${FRONT_END_IP}
    #   PROXY_IP: ${PROXY_IP}
    volumes:
      - ./:/backend
    # networks:
    #   - mynet
      
#   shishahub-phpmyadmin:
#     depends_on:
#       - docker-db
#     image: phpmyadmin/phpmyadmin
#     restart: unless-stopped
#     ports:
#       - '5001:80'
#     env_file: ./.env
#     environment:
#       PMA_HOST: docker-db 
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
# #     networks:
# #       - mynet

# volumes:
#   db_data: {}

networks:
  host:
    name: host
    external: true