version: '3.9' # optional since v1.27.0
services:

  shishahub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - '${PORT}:${PORT}'
    env_file: ./.env
    expose:
    - ${PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      SESSION_SECRET: ${SESSION_SECRET}
      VIRTUAL_HOST: ${VIRTUAL_HOST} # the incomming domain name for this site
      VIRTUAL_PORT: ${PORT} # the port your applicatio
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}  # the domain name to issue cert to
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} # this email can be any of your emails

networks:
  default:
    external:
      name: nginx-proxy